name: CI
on:
  push:
    branches:
      - main
      - master
      - '*v'
      - '*'
  pull_request:
    branches:
      - '**'
jobs:
  test:
    name: 'Ruby: ${{ matrix.ruby-version }}'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby-version: ['2.1', '2.2', '2.3', '2.4', '2.5', '2.6', '2.7', '3.0']
    steps:
      - uses: actions/checkout@v2
      - name: Install xmllint
        run: sudo apt-get install build-essential patch zlib1g-dev liblzma-dev
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: cd ext/mimemagic && bundle exec rake
      - run: bundle exec rake
